// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: hello.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// enum
type GetExampleRequest_SomeEnum int32

const (
	GetExampleRequest_UNKNOWN GetExampleRequest_SomeEnum = 0
	GetExampleRequest_HOGE    GetExampleRequest_SomeEnum = 1
	GetExampleRequest_FUGA    GetExampleRequest_SomeEnum = 2
)

// Enum value maps for GetExampleRequest_SomeEnum.
var (
	GetExampleRequest_SomeEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "HOGE",
		2: "FUGA",
	}
	GetExampleRequest_SomeEnum_value = map[string]int32{
		"UNKNOWN": 0,
		"HOGE":    1,
		"FUGA":    2,
	}
)

func (x GetExampleRequest_SomeEnum) Enum() *GetExampleRequest_SomeEnum {
	p := new(GetExampleRequest_SomeEnum)
	*p = x
	return p
}

func (x GetExampleRequest_SomeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetExampleRequest_SomeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_hello_proto_enumTypes[0].Descriptor()
}

func (GetExampleRequest_SomeEnum) Type() protoreflect.EnumType {
	return &file_hello_proto_enumTypes[0]
}

func (x GetExampleRequest_SomeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetExampleRequest_SomeEnum.Descriptor instead.
func (GetExampleRequest_SomeEnum) EnumDescriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{1, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{0}
}

//
// message: 構造体(KeyValue)
type GetExampleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 基本データ型
	SomeDouble   float64                        `protobuf:"fixed64,1,opt,name=some_double,json=someDouble,proto3" json:"some_double,omitempty"`
	SomeFloat    float32                        `protobuf:"fixed32,2,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	SomeInt32    int32                          `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeInt64    int64                          `protobuf:"varint,4,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint32   uint32                         `protobuf:"varint,5,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeUint64   uint64                         `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeSint32   int32                          `protobuf:"zigzag32,7,opt,name=some_sint32,json=someSint32,proto3" json:"some_sint32,omitempty"`
	SomeSint64   int64                          `protobuf:"zigzag64,8,opt,name=some_sint64,json=someSint64,proto3" json:"some_sint64,omitempty"`
	SomeFixed32  uint32                         `protobuf:"fixed32,9,opt,name=some_fixed32,json=someFixed32,proto3" json:"some_fixed32,omitempty"`
	SomeFixed64  uint64                         `protobuf:"fixed64,10,opt,name=some_fixed64,json=someFixed64,proto3" json:"some_fixed64,omitempty"`
	SomeSfixed32 int32                          `protobuf:"fixed32,11,opt,name=some_sfixed32,json=someSfixed32,proto3" json:"some_sfixed32,omitempty"`
	SomeSfixed64 int64                          `protobuf:"fixed64,12,opt,name=some_sfixed64,json=someSfixed64,proto3" json:"some_sfixed64,omitempty"`
	SomeBool     bool                           `protobuf:"varint,13,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeString   string                         `protobuf:"bytes,14,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBytes    []byte                         `protobuf:"bytes,15,opt,name=some_bytes,json=someBytes,proto3" json:"some_bytes,omitempty"`
	SomeMessage  *GetExampleRequest_SomeMessage `protobuf:"bytes,16,opt,name=some_message,json=someMessage,proto3" json:"some_message,omitempty"`
	// importしたmessage
	SomePartial *SomePartial               `protobuf:"bytes,17,opt,name=some_partial,json=somePartial,proto3" json:"some_partial,omitempty"`
	SomeEnum    GetExampleRequest_SomeEnum `protobuf:"varint,18,opt,name=some_enum,json=someEnum,proto3,enum=hello.GetExampleRequest_SomeEnum" json:"some_enum,omitempty"`
	// 配列
	SomeRepeatedString []string `protobuf:"bytes,19,rep,name=some_repeated_string,json=someRepeatedString,proto3" json:"some_repeated_string,omitempty"`
	// どちらか
	//
	// Types that are assignable to SomeOneof:
	//	*GetExampleRequest_OneofInt32
	//	*GetExampleRequest_OneofString
	SomeOneof isGetExampleRequest_SomeOneof `protobuf_oneof:"some_oneof"`
}

func (x *GetExampleRequest) Reset() {
	*x = GetExampleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleRequest) ProtoMessage() {}

func (x *GetExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleRequest.ProtoReflect.Descriptor instead.
func (*GetExampleRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{1}
}

func (x *GetExampleRequest) GetSomeDouble() float64 {
	if x != nil {
		return x.SomeDouble
	}
	return 0
}

func (x *GetExampleRequest) GetSomeFloat() float32 {
	if x != nil {
		return x.SomeFloat
	}
	return 0
}

func (x *GetExampleRequest) GetSomeInt32() int32 {
	if x != nil {
		return x.SomeInt32
	}
	return 0
}

func (x *GetExampleRequest) GetSomeInt64() int64 {
	if x != nil {
		return x.SomeInt64
	}
	return 0
}

func (x *GetExampleRequest) GetSomeUint32() uint32 {
	if x != nil {
		return x.SomeUint32
	}
	return 0
}

func (x *GetExampleRequest) GetSomeUint64() uint64 {
	if x != nil {
		return x.SomeUint64
	}
	return 0
}

func (x *GetExampleRequest) GetSomeSint32() int32 {
	if x != nil {
		return x.SomeSint32
	}
	return 0
}

func (x *GetExampleRequest) GetSomeSint64() int64 {
	if x != nil {
		return x.SomeSint64
	}
	return 0
}

func (x *GetExampleRequest) GetSomeFixed32() uint32 {
	if x != nil {
		return x.SomeFixed32
	}
	return 0
}

func (x *GetExampleRequest) GetSomeFixed64() uint64 {
	if x != nil {
		return x.SomeFixed64
	}
	return 0
}

func (x *GetExampleRequest) GetSomeSfixed32() int32 {
	if x != nil {
		return x.SomeSfixed32
	}
	return 0
}

func (x *GetExampleRequest) GetSomeSfixed64() int64 {
	if x != nil {
		return x.SomeSfixed64
	}
	return 0
}

func (x *GetExampleRequest) GetSomeBool() bool {
	if x != nil {
		return x.SomeBool
	}
	return false
}

func (x *GetExampleRequest) GetSomeString() string {
	if x != nil {
		return x.SomeString
	}
	return ""
}

func (x *GetExampleRequest) GetSomeBytes() []byte {
	if x != nil {
		return x.SomeBytes
	}
	return nil
}

func (x *GetExampleRequest) GetSomeMessage() *GetExampleRequest_SomeMessage {
	if x != nil {
		return x.SomeMessage
	}
	return nil
}

func (x *GetExampleRequest) GetSomePartial() *SomePartial {
	if x != nil {
		return x.SomePartial
	}
	return nil
}

func (x *GetExampleRequest) GetSomeEnum() GetExampleRequest_SomeEnum {
	if x != nil {
		return x.SomeEnum
	}
	return GetExampleRequest_UNKNOWN
}

func (x *GetExampleRequest) GetSomeRepeatedString() []string {
	if x != nil {
		return x.SomeRepeatedString
	}
	return nil
}

func (m *GetExampleRequest) GetSomeOneof() isGetExampleRequest_SomeOneof {
	if m != nil {
		return m.SomeOneof
	}
	return nil
}

func (x *GetExampleRequest) GetOneofInt32() int32 {
	if x, ok := x.GetSomeOneof().(*GetExampleRequest_OneofInt32); ok {
		return x.OneofInt32
	}
	return 0
}

func (x *GetExampleRequest) GetOneofString() string {
	if x, ok := x.GetSomeOneof().(*GetExampleRequest_OneofString); ok {
		return x.OneofString
	}
	return ""
}

type isGetExampleRequest_SomeOneof interface {
	isGetExampleRequest_SomeOneof()
}

type GetExampleRequest_OneofInt32 struct {
	OneofInt32 int32 `protobuf:"varint,20,opt,name=oneof_int32,json=oneofInt32,proto3,oneof"`
}

type GetExampleRequest_OneofString struct {
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

func (*GetExampleRequest_OneofInt32) isGetExampleRequest_SomeOneof() {}

func (*GetExampleRequest_OneofString) isGetExampleRequest_SomeOneof() {}

type GetExampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *GetExampleRequest `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *GetExampleResponse) Reset() {
	*x = GetExampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleResponse) ProtoMessage() {}

func (x *GetExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleResponse.ProtoReflect.Descriptor instead.
func (*GetExampleResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{2}
}

func (x *GetExampleResponse) GetRes() *GetExampleRequest {
	if x != nil {
		return x.Res
	}
	return nil
}

type StreamExampleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StreamExampleRequest) Reset() {
	*x = StreamExampleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExampleRequest) ProtoMessage() {}

func (x *StreamExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExampleRequest.ProtoReflect.Descriptor instead.
func (*StreamExampleRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{3}
}

func (x *StreamExampleRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type StreamExampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StreamExampleResponse) Reset() {
	*x = StreamExampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExampleResponse) ProtoMessage() {}

func (x *StreamExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExampleResponse.ProtoReflect.Descriptor instead.
func (*StreamExampleResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{4}
}

func (x *StreamExampleResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ネストしたmessage
type GetExampleRequest_SomeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hoge int32 `protobuf:"varint,1,opt,name=hoge,proto3" json:"hoge,omitempty"`
}

func (x *GetExampleRequest_SomeMessage) Reset() {
	*x = GetExampleRequest_SomeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExampleRequest_SomeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleRequest_SomeMessage) ProtoMessage() {}

func (x *GetExampleRequest_SomeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleRequest_SomeMessage.ProtoReflect.Descriptor instead.
func (*GetExampleRequest_SomeMessage) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetExampleRequest_SomeMessage) GetHoge() int32 {
	if x != nil {
		return x.Hoge
	}
	return 0
}

var File_hello_proto protoreflect.FileDescriptor

var file_hello_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x9a, 0x07, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x55, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x55, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x73, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x11, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x53, 0x69, 0x6e,
	0x74, 0x33, 0x32, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x73, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x18, 0x08, 0x20, 0x01, 0x28, 0x12, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x53, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x33, 0x32, 0x18, 0x09, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0b, 0x73, 0x6f, 0x6d, 0x65,
	0x46, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x6d, 0x65, 0x5f,
	0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0b, 0x73,
	0x6f, 0x6d, 0x65, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f,
	0x6d, 0x65, 0x5f, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0f, 0x52, 0x0c, 0x73, 0x6f, 0x6d, 0x65, 0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x10, 0x52, 0x0c, 0x73, 0x6f, 0x6d, 0x65, 0x53, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x36, 0x34, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x62, 0x6f, 0x6f,
	0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6f, 0x6d, 0x65, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x47, 0x0a, 0x0c, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x73,
	0x6f, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x73, 0x6f,
	0x6d, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x61, 0x6c, 0x52, 0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x12, 0x3e, 0x0a, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x12,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x6f, 0x6d, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08, 0x73, 0x6f, 0x6d, 0x65, 0x45, 0x6e, 0x75,
	0x6d, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x13, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x12, 0x73, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0b, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x6e, 0x65, 0x6f,
	0x66, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x23, 0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b,
	0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x21, 0x0a, 0x0b, 0x53,
	0x6f, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x6f, 0x67, 0x65, 0x22, 0x2b,
	0x0a, 0x08, 0x53, 0x6f, 0x6d, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x47, 0x45, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x55, 0x47, 0x41, 0x10, 0x02, 0x42, 0x0c, 0x0a, 0x0a, 0x73,
	0x6f, 0x6d, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x40, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x14, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x29, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0xc3, 0x01, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x25, 0x0a, 0x05, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x12, 0x0c, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0c, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12,
	0x18, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hello_proto_rawDescOnce sync.Once
	file_hello_proto_rawDescData = file_hello_proto_rawDesc
)

func file_hello_proto_rawDescGZIP() []byte {
	file_hello_proto_rawDescOnce.Do(func() {
		file_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_hello_proto_rawDescData)
	})
	return file_hello_proto_rawDescData
}

var file_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hello_proto_goTypes = []interface{}{
	(GetExampleRequest_SomeEnum)(0),       // 0: hello.GetExampleRequest.SomeEnum
	(*Empty)(nil),                         // 1: hello.Empty
	(*GetExampleRequest)(nil),             // 2: hello.GetExampleRequest
	(*GetExampleResponse)(nil),            // 3: hello.GetExampleResponse
	(*StreamExampleRequest)(nil),          // 4: hello.StreamExampleRequest
	(*StreamExampleResponse)(nil),         // 5: hello.StreamExampleResponse
	(*GetExampleRequest_SomeMessage)(nil), // 6: hello.GetExampleRequest.SomeMessage
	(*SomePartial)(nil),                   // 7: hello.SomePartial
}
var file_hello_proto_depIdxs = []int32{
	6, // 0: hello.GetExampleRequest.some_message:type_name -> hello.GetExampleRequest.SomeMessage
	7, // 1: hello.GetExampleRequest.some_partial:type_name -> hello.SomePartial
	0, // 2: hello.GetExampleRequest.some_enum:type_name -> hello.GetExampleRequest.SomeEnum
	2, // 3: hello.GetExampleResponse.res:type_name -> hello.GetExampleRequest
	1, // 4: hello.Hello.Greet:input_type -> hello.Empty
	2, // 5: hello.Hello.GetExample:input_type -> hello.GetExampleRequest
	4, // 6: hello.Hello.StreamExample:input_type -> hello.StreamExampleRequest
	1, // 7: hello.Hello.Greet:output_type -> hello.Empty
	3, // 8: hello.Hello.GetExample:output_type -> hello.GetExampleResponse
	5, // 9: hello.Hello.StreamExample:output_type -> hello.StreamExampleResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hello_proto_init() }
func file_hello_proto_init() {
	if File_hello_proto != nil {
		return
	}
	file_partial_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExampleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamExampleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamExampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExampleRequest_SomeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hello_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetExampleRequest_OneofInt32)(nil),
		(*GetExampleRequest_OneofString)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hello_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_proto_goTypes,
		DependencyIndexes: file_hello_proto_depIdxs,
		EnumInfos:         file_hello_proto_enumTypes,
		MessageInfos:      file_hello_proto_msgTypes,
	}.Build()
	File_hello_proto = out.File
	file_hello_proto_rawDesc = nil
	file_hello_proto_goTypes = nil
	file_hello_proto_depIdxs = nil
}
